apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
spec:
  destination:
    name: ''
    namespace: consul
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.31.1
    chart: consul
    helm:
      values: |-
        global:
          datacenter: blizzard
          name: consul
          image: hashicorp/consul:1.9.3
          imageEnvoy: jsiebens/envoy-arm64:1.13.3

        connectInject:
          enabled: true
          healthChecks:
            enabled: true

        server:
          replicas: 3
          bootstrapExpect: 3
          storage: 1Gi
          storageClass: coldbrew-storage
          exposeGossipAndRPCPorts: true
          ports:
            serflan:
              port: 9301
          metrics:
            enabled: true
            enableAgentMetrics: true

        client:
          exposeGossipPorts: true

        ingressGateways:
          enabled: true
          defaults:
            service:
              type: LoadBalancer

        controller:
          enabled: true

        ui:
          ingress:
            enabled: true
            hosts:
              - host: consul.coldbrew.labs
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks