apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    name: ''
    namespace: vault
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.10.0
    chart: vault
    helm:
      values: |-
        injector:
          enabled: true

        server:
          ha:
            enabled: true
            replicas: 2
            config: |
              ui = true
              listener "tcp" {
                tls_disable     = 1
                address         = "[::]:8200"
                cluster_address = "[::]:8201"
              }

              storage "consul" {
                path   = "vault"
                address = "HOST_IP:8500"
              }

              telemetry {
                prometheus_retention_time = "30s"
                disable_hostname          = true
              }

        ui:
          enabled: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks