consul_local_binary: true

consul_datacenter: 'blizzard'
consul_server_list: ['192.168.100.130','192.168.100.129','192.168.100.128']

consul_enable_tls: true
consul_tls_ca_file: 'tls/consul-agent-ca.pem'
consul_tls_cert_file: 'tls/blizzard-server-consul-0.pem'
consul_tls_key_file: 'tls/blizzard-server-consul-0-key.pem'

vault_local_binary: true

vault_storage_backend: 'consul'

vault_tls_disable: false
vault_tls_cert_file: 'tls/vault.crt'
vault_tls_key_file: 'tls/vault.key'