---
- hosts: all
  become: yes
  tasks:
    - name: Stop K3s service
      ansible.builtin.systemd:
        name: k3s
        state: stopped
        enabled: no
      when: "'controllers' in group_names"

    - name: Stop K3s service
      ansible.builtin.systemd:
        name: k3s-worker
        state: stopped
        enabled: no
      when: "'workers' in group_names"

    - name: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
      register: pkill_containerd_shim_runc
      command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
      changed_when: "pkill_containerd_shim_runc.rc == 0"
      failed_when: false

    - name: Umount k3s filesystems
      include_tasks: umount_with_children.yml
      with_items:
        - /run/k3s
        - /var/lib/kubelet
        - /run/netns
        - /var/lib/rancher/k3s
      loop_control:
        loop_var: mounted_fs

    - name: Remove service files, binaries and data
      file:
        name: "{{ item }}"
        state: absent
      with_items:
        - /usr/local/bin/k3s
        - /etc/systemd/system/k3s.service"
        - /etc/systemd/system/k3s-node.service"
        - /etc/rancher/k3s
        - /var/lib/kubelet
        - /var/lib/rancher/k3s

    - name: Reload daemons
      systemd:
        daemon_reload: yes

    - name: Reboot
      ansible.builtin.reboot:

    - name: Wait 200 seconds, but only start checking after 15 seconds
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 200