---
kind: Namespace
apiVersion: v1
metadata:
  name: transmission
  labels:
    name: transmission
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: transmission
spec:
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: linuxserver/transmission
        env:
          - name: PGID
            value: '1001'
          - name: PUID
            value: '1001'
        volumeMounts:
        - name: downloads
          mountPath: /downloads
        - name: config
          mountPath: /config
        - name: watch
          mountPath: /watch
        ports:
        - containerPort: 9091
          name: transmission-ui
      volumes:
      - name: downloads
        hostPath:
          path: /array/transmission/downloads
          type: DirectoryOrCreate
      - name: config
        hostPath:
          path: /array/transmission/config
          type: DirectoryOrCreate
      - name: watch
        hostPath:
          path: /array/transmission/watch
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-ui
  namespace: transmission
spec:
  selector:
    app: transmission
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091