kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: vault-ui
  namespace: vault
spec:
  rules:
    - host: "vault.coldbrew.labs"
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: vault-ui
                port:
                  number: 8200
